### ISSUE TITLE
[Suggestions] PBE + ECB

### ISSUE THREAD

**Issue by kexinoh** [CROSSINGTUD/CamBench#5]
There are some issues with the author's dataset
PBE generally requires no less than 1000 times, while the value set by the author is 1000, which is generally 999 in other datasets
2. Introducing ECB in calling RSA.
These are some of my suggestions, I hope the author can refer to them.

**Comment by akwick** [comment]
Thanks for reaching out and your patience. 

##### PBE
I assume that you refer to CamBenchCAP due to the PBE value of 1,000, e.g., [PBEParameters2.java](https://github.com/CROSSINGTUD/CamBench/blob/main/CamBench_Cap/src/main/java/org/cambench/cap/basic/pbeparameters/PBEParameters2.java). I agree that we derivate from the value commonly used in other datasets to reflect recent developments. We discussed this design decision in more detail in the README file of [CamBenchCap](https://github.com/CROSSINGTUD/CamBench/tree/main/CamBench_Cap#password-based-key-derivation-functions---iteration-count). 
Do you agree with this assessment or would you wish for more details? If yes, where would you appreciate this information?

##### RSA in ECB
Again, my assumption is that you refer to the test cases of CamBenchCAP, e.g., [SmallKeySize1.java](https://github.com/CROSSINGTUD/CamBench/blob/592bf3b115e0f39f7bc1e830091c0ec3f6794966/CamBench_Cap/src/main/java/org/cambench/cap/objectsensitivity/truepositive/smallkeysize/SmallKeySize1.java).
ECB is indeed insecure if it is used to chain multiple blocks, for block ciphers, such as AES. However, RSA is not a block cipher and the JCA as well as BouncyCastle ignores this value. 
Which information or change would you expect to address your suggestion?

Thanks for reaching out, and I'm looking forward to your thoughts.
Best, Anna.
